export const ADS_PREVIEW_DATA = {
  ads_space: {
    id: 'preview-space-portable-power',
    slug: 'portable-power-stations',
    name: 'Portable Power Stations',
    locale: 'US/en',
    platform: 'ChatGPT Ads',
    model: 'GPT-4.1',
    query_topic: 'backup power, outage prep, and camping energy',
    advertiser_count: 3,
    observed_card_count: 3,
    total_appearances: 9,
    last_observed_at: '2026-06-06T00:00:00Z',
    source_mode: 'embedded_preview',
    fixture: true,
  },
  advertiser_leaderboard: [
    {
      advertiser: {
        id: 'preview-advertiser-jackery',
        type: 'advertiser',
        name: 'Jackery',
        domain: 'jackery.com',
        logo_url: '../../logos/openai.png',
        official_url: 'https://www.jackery.com',
      },
      observed_card_count: 1,
      total_appearances: 4,
      latest_observed_at: '2026-06-06T00:00:00Z',
    },
    {
      advertiser: {
        id: 'preview-advertiser-bluetti',
        type: 'advertiser',
        name: 'Bluetti',
        domain: 'bluettipower.com',
        logo_url: '../../logos/perplexity.png',
        official_url: 'https://www.bluettipower.com',
      },
      observed_card_count: 1,
      total_appearances: 3,
      latest_observed_at: '2026-06-05T00:00:00Z',
    },
    {
      advertiser: {
        id: 'preview-advertiser-anker',
        type: 'advertiser',
        name: 'Anker SOLIX',
        domain: 'anker.com',
        logo_url: '../../logos/google.png',
        official_url: 'https://www.anker.com',
      },
      observed_card_count: 1,
      total_appearances: 2,
      latest_observed_at: '2026-06-04T00:00:00Z',
    },
  ],
  observed_cards: [
    {
      id: 'preview-card-home-backup',
      advertiser: {
        id: 'preview-advertiser-jackery',
        type: 'advertiser',
        name: 'Jackery',
        domain: 'jackery.com',
        logo_url: '../../logos/openai.png',
        official_url: 'https://www.jackery.com',
      },
      creative_asset: {
        id: 'preview-creative-home-backup',
        image_url: '../../ads-fixtures/home-backup-card.svg',
        source_image_url: '../../ads-fixtures/home-backup-card.svg',
        cached_image_url: '../../ads-fixtures/home-backup-card.svg',
        mime_type: 'image/svg+xml',
        width_px: 1200,
        height_px: 900,
      },
      title: 'Home backup power without generator noise',
      description: 'Expandable battery system positioned for blackout prep and whole-home runtime.',
      destination_url: 'https://www.jackery.com/products/solar-generator-2000-plus',
      appearance_count: 4,
      first_seen_at: '2026-05-30T00:00:00Z',
      last_seen_at: '2026-06-06T00:00:00Z',
      contexts: [
        {
          id: 'preview-context-home-backup',
          observed_query: 'best portable power station for home backup',
          query_topic: 'home backup comparison',
          country_code: 'US',
          language_code: 'en',
          model_name: 'GPT-4.1',
          observed_at: '2026-06-06T00:00:00Z',
          platform: {
            id: 'preview-platform-chatgpt',
            type: 'platform',
            name: 'ChatGPT',
            domain: 'openai.com',
            logo_url: '../../logos/openai.png',
            official_url: 'https://openai.com',
          },
          channel: {
            id: 'preview-channel-chatgpt',
            type: 'channel',
            name: 'ChatGPT Ads',
            domain: 'chatgpt.com',
            logo_url: '../../logos/openai.png',
            official_url: 'https://chatgpt.com',
          },
        },
      ],
    },
    {
      id: 'preview-card-caravan',
      advertiser: {
        id: 'preview-advertiser-bluetti',
        type: 'advertiser',
        name: 'Bluetti',
        domain: 'bluettipower.com',
        logo_url: '../../logos/perplexity.png',
        official_url: 'https://www.bluettipower.com',
      },
      creative_asset: {
        id: 'preview-creative-caravan',
        image_url: '../../ads-fixtures/caravan-card.svg',
        source_image_url: '../../ads-fixtures/caravan-card.svg',
        cached_image_url: '../../ads-fixtures/caravan-card.svg',
        mime_type: 'image/svg+xml',
        width_px: 1200,
        height_px: 900,
      },
      title: 'Solar generator built for caravan travel',
      description: 'AU-targeted creative focused on 240V support and solar recharge on the road.',
      destination_url: 'https://www.bluettipower.com/products/ac200l-portable-power-station',
      appearance_count: 3,
      first_seen_at: '2026-05-29T00:00:00Z',
      last_seen_at: '2026-06-05T00:00:00Z',
      contexts: [
        {
          id: 'preview-context-caravan',
          observed_query: 'solar generator for caravan australia',
          query_topic: 'caravan and camping',
          country_code: 'AU',
          language_code: 'en',
          model_name: 'GPT-4.1',
          observed_at: '2026-06-05T00:00:00Z',
          platform: {
            id: 'preview-platform-chatgpt',
            type: 'platform',
            name: 'ChatGPT',
            domain: 'openai.com',
            logo_url: '../../logos/openai.png',
            official_url: 'https://openai.com',
          },
          channel: {
            id: 'preview-channel-chatgpt',
            type: 'channel',
            name: 'ChatGPT Ads',
            domain: 'chatgpt.com',
            logo_url: '../../logos/openai.png',
            official_url: 'https://chatgpt.com',
          },
        },
      ],
    },
    {
      id: 'preview-card-emergency',
      advertiser: {
        id: 'preview-advertiser-anker',
        type: 'advertiser',
        name: 'Anker SOLIX',
        domain: 'anker.com',
        logo_url: '../../logos/google.png',
        official_url: 'https://www.anker.com',
      },
      creative_asset: {
        id: 'preview-creative-emergency',
        image_url: '../../ads-fixtures/emergency-card.svg',
        source_image_url: '../../ads-fixtures/emergency-card.svg',
        cached_image_url: '../../ads-fixtures/emergency-card.svg',
        mime_type: 'image/svg+xml',
        width_px: 1200,
        height_px: 900,
      },
      title: 'Emergency-ready battery backup for outages',
      description: 'Preparedness messaging highlighting indoor-safe backup power and rapid recharge.',
      destination_url: 'https://www.anker.com/products/a1780',
      appearance_count: 2,
      first_seen_at: '2026-05-28T00:00:00Z',
      last_seen_at: '2026-06-04T00:00:00Z',
      contexts: [
        {
          id: 'preview-context-emergency',
          observed_query: 'battery backup for power outage',
          query_topic: 'emergency preparedness',
          country_code: 'US',
          language_code: 'en',
          model_name: 'GPT-4.1',
          observed_at: '2026-06-04T00:00:00Z',
          platform: {
            id: 'preview-platform-chatgpt',
            type: 'platform',
            name: 'ChatGPT',
            domain: 'openai.com',
            logo_url: '../../logos/openai.png',
            official_url: 'https://openai.com',
          },
          channel: {
            id: 'preview-channel-chatgpt',
            type: 'channel',
            name: 'ChatGPT Ads',
            domain: 'chatgpt.com',
            logo_url: '../../logos/openai.png',
            official_url: 'https://chatgpt.com',
          },
        },
      ],
    },
  ],
  quality: {
    fixture: true,
    cards_returned: 3,
    hidden_cards_missing_images: 0,
    data_source: 'embedded_preview',
    cleaning_rules: [
      'cards require advertiser identity, title, destination URL, and at least one query context',
      'cards without a nonblank creative image are excluded',
      'platform and channel chips must include official logo plus name',
      'query context keeps query, topic, country, language, model, and observed timestamp',
    ],
  },
} as const
